### ISSUE TITLE
Weaopn Loadout

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/Treachery#29]
Player Loadouts
* Player has a set number of weapon loadouts
* Can scroll, hit number pad, or bumpers on weapon to select between them
* Player actions you can take are determined by current loadout
* Loadout properties
  * Main Item
    * Either 1H or 2H
    * Is it a ranged or melee weapon?
    * Goes in player's dominant hand (left or right handed)
* If 1H weapon
  * Can have offhand item
  * If holding a ranged weapon and a shield…
    * No more aim down sights mechanic or steady aim
    * If holding a melee weapon and a shield…
  * Attack rate penalty of 50% for now…
    * Offhand item can apply some property to the weapon as well or environment affect

Features left to add

- [x] Dropping Items Closed in PR #38 
- [x] Swapping Items Closed in PR #39 
- [ ] Configurable cooldown on swap items Closed in PR #40

**Comment by nicholas-maltbie** [comment]
Added basic items in PR #32 

Still need to add swapping items and dropping items in front of the player (instead of below them).

**Comment by nicholas-maltbie** [comment]
Additional mechanic: load out swap cooldown.

Add a basic cooldown (maybe 1 second for now) for when swapping items will be available.
