### ISSUE TITLE
Have player stamina and combat setup

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/Treachery#3]
Player Interactions
- [x] Have player death and health…. Because yeah - Added in PR #9 
- [x] Have basic combat system stamina based
    - [x] Attack
        - [x] Basic melee attack - Added in PR #10 
        - [x] Basic ranged attack
          - [x] Static attack from archer NPC - Added in PR #15 
          - [ ] #26
    - [x] Dodge - Added in PR #11 
        - [x] Add dodge invulnerability frames for player - Added in PR #17 
    - [x] #21 - Added in PR #20
        - [x] #22 - Added in PR #20
    - [x] Sprint (flee) - Already part of base character controller.
- [x] Use as bar of stamina to do something like combat or room interaction - Added in PR #23 
    - [x] Bars of stamina retore at a fixed rate (like 1 per second) - Added in PR #23 
    - [x] Doing actions takes stamina. - Added in PR #23

**Comment by nicholas-maltbie** [comment]
Added some player death and health as part of PR #9 

https://user-images.githubusercontent.com/3240136/219612651-f9469741-2db8-40b4-b3ca-1c526c061608.mp4

**Comment by nicholas-maltbie** [comment]
Final reviews and reworks with @jkdenny1497  included in PR #25
