### ISSUE TITLE
Melee Weapons

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/Treachery#30]
## Overview
* Attack in direction camera is facing
  * [ ] Have player slowly rotate towards camera direction for all players
* Properties
  * [x] 1H or 2H - Already component of items!
  * [x] Damage per attack - Addressed in PR #45
  * [x] Attack Rate/Cooldown between attacks - Addressed in PR #45
  * Attack type
    * [x] Single Target - Addressed in PR #45 
    * [x] Cleave - Added in PR #51 
    * [x] Pierce - Added in PR #51 
  * Attack modifiers
    * [x] Armor piercing, bludgeoning, elemental, etc… - Addressed in PR #45
    * [x] Attack arc size - Addressed in PR #45
    * [ ] Max target count
    * [ ] Damage reduction for multiple targets
    * [x] Attack range (in dnd this reach)- Addressed in PR #45

## Finding Targets
* When attacking melee weapons attack in arc (weapon like a punch maybe only has 30 degrees)
* When hitting a single target
  * Prefer target closest to center of frame, then target that is closest by distance\
    ![image](https://user-images.githubusercontent.com/3240136/222884262-6bbaea95-47c9-4322-a23f-a0580911c48f.png)
* Attack has a cleave
  * Hit everyone in the frame of view for the player
  * Have damage falloff factor where damage is reduced by x% per target hit
  * Max number of targets is optional parameter
  * Have swing direction hit targets in order left to right/right to left
    ![image](https://user-images.githubusercontent.com/3240136/222884372-f12f3b97-5a46-4501-9aec-44a0a743815f.png)
* Attack that has pierce
  * Draw a line out in front of the character and hit all targets
  * Have damage falloff factor where damage is reduced by x% per target hit
  * Max number of targets is optional parameter
    ![image](https://user-images.githubusercontent.com/3240136/222884409-ee848ba8-4bc8-48e7-a73b-a4b9d0262b9b.png)
